### ISSUE TITLE
从0到生成一个项目怎么玩？

### ISSUE THREAD

**Issue by 0muxi0** [cai3178940/youran#3]
目前在本地运行起了代码生成工具，但是怎么逆向生成项目呢。可以举一个简单的详细例子么？比如生成一个user增删改查的简单工程

**Comment by cai3178940** [comment]
这是一个简单的
<a href="https://github.com/cai3178940/youran/releases/tag/v.3.0.0" target="_blank">项目示例</a>，
您只需要下载项目的元数据文件，然后按照下面的流程，简单地点几下，即可预览生成的代码

1. 项目管理 -> 元数据导入
2. 项目管理 -> 操作 -> 编辑 -> 选择代码模板
3. 项目管理 -> 操作 -> 代码预览
