### ISSUE TITLE
前端代码模板，怎么生成工程？

### ISSUE THREAD

**Issue by fuxuzhi** [cai3178940/youran#5]
已经导入了您提供的前端模板代码，但是创建项目之后，还要在建一遍实体表吗？

**Comment by fuxuzhi** [comment]
[
![QQ截图20200113153200](https://user-images.githubusercontent.com/38277848/72238832-f7575700-3619-11ea-9089-23cc4f008a8a.jpg)
](url)
在创建完后台项目后，可以正常生成项目，但是前端创建项目之后，还需要将后端所有的实体表在重新创建一遍吗？

**Comment by fuxuzhi** [comment]
如果后端项目手动创建了一遍实体表，前端项目是否需要在重复创建一遍呢？工作量有点大，有没有简单的方法呢？

**Comment by cai3178940** [comment]
不需要重新创建一遍，你这里报错估计是前端模板的bug导致，发一下后端的报错日志，最好是能把项目元数据导出来发给我，我就能复现这个bug

**Comment by fuxuzhi** [comment]
我debug了下后端日志，大概知道什么原因了。现在创建前端项目时，配置好基本信息，还需要创建实体以及字段，但是我在后端项目中已经创建过了。因此，我现在的做法是，**先导出后端项目元数据，然后在重新导入，修改git地址、以及模板改成前端模板，这样实体就能保持一致了**。不知道，您是怎么生成前端工程的？

**Comment by cai3178940** [comment]
单个项目可以同时指定前后端两套模板

![image](https://user-images.githubusercontent.com/12594166/72357900-b26d1680-3726-11ea-8816-10eeb26abe10.png)
